### ISSUE TITLE
[Bug] Database is Locked

### ISSUE THREAD

**Issue by RinNiko** [Insprill/damage-indicator#22]
I'm on paper 1.12.2 lastest plugin version

keep gettings this error spamming on console

[16:13:01 WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
>
 [16:13:01 WARN]:       at org.sqlite.core.DB.newSQLException(:909)
>
 [16:13:01 WARN]:       at org.sqlite.core.DB.newSQLException(:921)
>
 [16:13:01 WARN]:       at org.sqlite.core.DB.execute(:822)
>
 [16:13:01 WARN]:       at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(:53)
>
 [16:13:01 WARN]:       at com.zenya.damageindicator.file.DBFile.sendQueryStatement(DBFile.java:98)
>
 [16:13:01 WARN]:       at com.zenya.damageindicator.file.DBFile.sendPreparedStatement(DBFile.java:77)
>
 [16:13:01 WARN]:       at com.zenya.damageindicator.file.DBFile.initData(DBFile.java:125)
>
 [16:13:01 WARN]:       at com.zenya.damageindicator.file.DBFile.getToggleStatus(DBFile.java:129)
>
 [16:13:01 WARN]:       at com.zenya.damageindicator.storage.ToggleManager.lambda$isToggled$0(ToggleManager.java:38)
>
 [16:13:01 WARN]:       at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(:64)
>
 [16:13:01 WARN]:       at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(:52)
>
 [16:13:01 WARN]:       at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(:22)
>
 [16:13:01 WARN]:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>
 [16:13:01 WARN]:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>
 [16:13:01 WARN]:       at java.lang.Thread.run(Thread.java:748)

**Comment by Insprill** [comment]
Does it continue to occur after a full server restart, and when does it happen?

**Comment by Insprill** [comment]
I'd strongly suggest not using Plugman or other solutions for hot-reloading servers as they're very likely to break most plugins, as seen here.
