### ISSUE TITLE
[Bug] SQL Query data base busy.

### ISSUE THREAD

**Issue by RinNiko** [Insprill/damage-indicator#23]
**Paper 1.12.2**

**Error spamming on the console. (Possible to disable SQL function ?)**
[21:18:01 WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
>
 [21:18:01 WARN]:       at org.sqlite.core.DB.newSQLException(:909)
>
 [21:18:01 WARN]:       at org.sqlite.core.DB.newSQLException(:921)
>
 [21:18:01 WARN]:       at org.sqlite.core.DB.throwex(:886)
>
 [21:18:01 WARN]:       at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
>
 [21:18:01 WARN]:       at org.sqlite.core.NativeDB.prepare(:127)
>
 [21:18:01 WARN]:       at org.sqlite.core.DB.prepare(:227)
>
 [21:18:01 WARN]:       at org.sqlite.core.CorePreparedStatement.<init>(:41)
>
 [21:18:01 WARN]:       at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(:30)
>
 [21:18:01 WARN]:       at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(:19)
>
 [21:18:01 WARN]:       at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(:48)
>
 [21:18:01 WARN]:       at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(:263)
>
 [21:18:01 WARN]:       at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(:235)
>
 [21:18:01 WARN]:       at com.zenya.damageindicator.file.DBFile.sendQueryStatement(DBFile.java:91)
>
 [21:18:01 WARN]:       at com.zenya.damageindicator.file.DBFile.sendPreparedStatement(DBFile.java:77)
>
 [21:18:01 WARN]:       at com.zenya.damageindicator.file.DBFile.initData(DBFile.java:125)
>
 [21:18:01 WARN]:       at com.zenya.damageindicator.file.DBFile.getToggleStatus(DBFile.java:129)
>
 [21:18:01 WARN]:       at com.zenya.damageindicator.storage.ToggleManager.lambda$isToggled$0(ToggleManager.java:38)
>
 [21:18:01 WARN]:       at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(:64)
>
 [21:18:01 WARN]:       at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(:52)
>
 [21:18:01 WARN]:       at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(:22)
>
 [21:18:01 WARN]:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>
 [21:18:01 WARN]:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>
 [21:18:01 WARN]:       at java.lang.Thread.run(Thread.java:748)

**Comment by Insprill** [comment]
Please create separate issues for different bugs/requests. Did you reload with plugin with something like plugman? If so do a full server restart.

**Comment by RinNiko** [comment]
Yes, I have done a full restart I will separate it. I will keep Error Spamming Here.

**Comment by RinNiko** [comment]
How this going on @Insprill it spam too much I can't use it anymore T_T. Why we need DB connect on Hologram plugin? Can we disable it?

**Comment by Insprill** [comment]
I'll look into it this weekend, maybe earlier if I have time. It uses a database to store players' toggle states. I've wanted to get rid of the db for a little while now, but it'll be a decent bit of work that I haven't had the time for. Unfortunately, there's no way to disable it. Please try deleting the database when the server is stopped and see if that fixes the error spam; you're the only one to have reported this so it's possible something in the db got corrupted and is causing the lock.

**Comment by Insprill** [comment]
I believe I figured out what's causing this, and I'm surprised you're the only one who has encountered it. In about an hour as of writing, you'll be able to download a dev build with a fix [here](https://github.com/Insprill/damage-indicator/actions/runs/8313988055). Please test that out and see if the issue persists.
